version: '3.8'

services:
  ms_event_manager:
    build:
      context: ./ms_event_manager
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - RABBITMQ_HOST=rabbitmq
      - MONGO_URI=mongodb+srv://root:Ykmxxi1iqoqS7NWP@cluster0.mongodb.net/db_event
    restart: always

  ms_ticket_manager:
    build:
      context: ./ms_ticket_manager
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - RABBITMQ_HOST=rabbitmq
      - MONGO_URI=mongodb+srv://root:Ykmxxi1iqoqS7NWP@cluster0.mongodb.net/db_ticket
      - MS_EVENT_MANAGER_URL=http://ms_event_manager:8080/events/v1
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
